packageExtensions:
  "@npmcli/metavuln-calculator@*":
    peerDependencies:
      json-parse-even-better-errors: "*"
  "@snowpack/web-test-runner-plugin@*":
    peerDependencies:
      magic-string: "*"
      tar: "*"
  bin-links@*:
    peerDependencies:
      mkdirp-infer-owner: "*"
  eslint-module-utils@*:
    peerDependencies:
      "@typescript-eslint/parser": "*"
      eslint-import-resolver-node: "*"
  eslint-plugin-import@*:
    peerDependencies:
      "@typescript-eslint/parser": "*"
      eslint-import-resolver-node: "*"
  graphile-build-pg@*:
    peerDependencies:
      graphql: "*"
  skypack@*:
    peerDependencies:
      tar: "*"
  snowpack@*:
    peerDependencies:
      magic-string: "*"
      tar: "*"
      regenerator-runtime: "*"
  typeorm@*:
    peerDependencies:
      pg: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"


yarnPath: .yarn/releases/yarn-berry.cjs
nodeLinker: "node-modules"